version: '{branch}/{build}'
image:
  - macos
  - Ubuntu2004
  - Visual Studio 2019
stack: python 3.8
build_script:
  - ps: |
      if ($isWindows) {
          if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") {
              $compilerVersion = "14"
              $cmakeGenerator = "Visual Studio 14 2015"
          }
          if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") {
              $compilerVersion = "15"
              $cmakeGenerator = "Visual Studio 15 2017"
          }
          if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019") {
              $compilerVersion = "16"
              $cmakeGenerator = "Visual Studio 16 2019"
          }
          & "C:\Python38-x64\python.exe" -m pip install --user conan
          $env:PATH += ";C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts"
      } else {
          $cmakeGenerator = "Unix Makefiles"
          pip install conan
          $env:PATH += ":/home/appveyor/.local/bin"
          conan profile new default --detect
          if ($isLinux) {
              conan profile update settings.compiler.libcxx=libstdc++11 default
          } else {
              conan profile update settings.compiler.libcxx=libc++ default
          }
      }
      mkdir build
      cd build
      conan install -s build_type=Debug ..
      cmake -G "$cmakeGenerator" -DCMAKE_BUILD_TYPE=Debug -DSIMDEE_BUILD_TESTS:BOOL=ON ..
      cmake --build . --config "Debug"
test_script:
  - ps: ctest -C Debug
