language: cpp
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - LIBCXX=libstdc++11
        - PATH="${HOME}/Library/Python/2.7/bin:${PATH}"
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      env:
        - MATRIX_EVAL=""
        - LIBCXX=libc++
        - PATH="${HOME}/Library/Python/2.7/bin:${PATH}"
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - LIBCXX=libstdc++11
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - LIBCXX=libstdc++11
    - os: linux
      arch: arm64
      dist: bionic
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - LIBCXX=libstdc++11
        - EXTRA_CMAKE="-DSIMDEE_AARCH64:BOOL=ON"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - pip install --user conan
  - conan remote add catchorg https://api.bintray.com/conan/catchorg/Catch2
  - conan install -s build_type=Release -s compiler.libcxx=${LIBCXX} ..
  - cmake -DCMAKE_BUILD_TYPE=Release -DSIMDEE_BUILD_TESTS:BOOL=ON ${EXTRA_CMAKE} ..
  - cmake --build .
  - ctest
